# Generated by Django 3.2.5 on 2021-07-30 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hospadmin',
            new_name='Hosp',
        ),
    ]
